name: exchangilymobileapp
description: Decentralized Wallet App.

version: 2.1.36+175
environment:
  sdk: ">=2.7.0 <3.0.0"

dependency_overrides:
  intl: any

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  local_auth: ^1.1.8

  # ----- Bitcoin -- Addresses -- Bip

  bs58check: ^1.0.1

  # bch address
  bitbox: ^0.0.1

  # Generate LTC and DOGE coin address
  bitcoin_flutter: ^2.0.1

  #bip39: ^1.0.3

  # ----- ICONS ---------

  # Cupertino Icons
  cupertino_icons: ^1.0.0

  # Font Awesome
  font_awesome_flutter: ^9.1.0

  # ----- COMMUNICATION --------

  # Http
  http: ^0.12.0+2

  # Web Sockets
  web_socket_channel: ^1.1.0

  # ----- SECURITY --------

  # Encrypt
  encrypt: ^4.0.3

  # Logger
  logger: ^1.1.0

  # Web 3 Dart
  web3dart:
    ^1.2.1

    # ----- ARCHITECTURE --------

  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^5.0.0

  # Dependency injection
  get_it: ^7.2.0

  # State Management
  stacked: ^2.1.9

  # Path Provider
  path_provider: ^2.0.4

  # Random String
  random_string: ^2.0.1

  # Keccak
  keccak: ^1.0.3

  # Json Serialization
  # json_serializable: ^2.2.1

  # Generate QR Code Image
  qr_flutter: ^4.0.0
  qr: ^2.1.0

  # Barcode Scan
  barcode_scan: 3.0.1
  #barcode_scan: ^2.0.2

  # Material icons
  material_design_icons_flutter: ^4.0.5345

  # Flushbar instead of Snackbar for notifications
  #flushbar: ^1.9.0
  flushbar:
    git:
      url: git://github.com/valterh4ck3r/flushbar
      ref: master

  # decimal
  decimal: ^1.3.0

  # Device Preview
  # device_preview:

  #webview_flutter
  #webview_flutter: ^0.3.19+4

  # rflutter Alert
  rflutter_alert: ^2.0.4

  # Shared Preferences
  shared_preferences: ^2.0.7

  # Loading animation
  shimmer: ^2.0.0

  # Sqflite
  sqflite: ^2.0.0+4

  # Path
  path: ^1.6.4

  # Build version
  package_info: ^2.0.2

  # Pull to refresh
  pull_to_refresh: ^2.0.0

  # Flutter SVG
  flutter_svg: ^0.19.2+1

  # Carousel
  flutter_swiper: ^1.1.6

  # validators
  validators: ^3.0.0

  # cached_network_image
  cached_network_image: ^2.0.0

  #gradient_text
  gradient_text: ^1.0.2

  #drop_cap_text
  drop_cap_text: ^1.0.7

  # launch the app in the app stores
  launch_review: ^3.0.1

  # To open web url's
  # ERROR
  # Flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.5.2\android\src\main\java\io\flutter\plugins\
  # urllauncher\WebViewActivity.java uses or overrides a deprecated API
  url_launcher: ^6.0.10

  # # video_player
  # fijkplayer:

  #youtube_player
  youtube_player_flutter: ^8.0.0

  #flutter_html
  flutter_html: ^1.2.0

  #flutter_local_notifications
  # flutter_local_notifications: ^1.4.4+4

  # #share
  share_plus: ^2.1.4

  json_diff: 0.2.0

  # Share files
  # share:
  #   git:
  #     url: https://github.com/bbedward/plugins.git
  #     path: packages/share
  #     ref: master

  # json_diff:
  #   git:
  #     url: https://github.com/google/dart-json_diff.git
  #     ref: master
  # To highlight new feature or how to use tuts
  showcaseview: ^1.1.1

  # Connectivity
  connectivity: ^3.0.6

  # Reactive
  observable_ish:

  # Pagination
  #pagination_view: ^1.0.3+2

  # Overlay notification
  overlay_support: ^1.2.0

  # Reload app
  #flutter_phoenix: ^0.1.0

  # auto size text
  auto_size_text: ^2.1.0

  # protobuf
  protobuf: ^1.1.1

  # protoc_plugin
  protoc_plugin: ^19.3.1

  intl_translation: ^0.17.0

  #version
  version: ^2.0.0

dev_dependencies:
  intl: ^0.17.0
  # flutter_launcher_icons: ^0.7.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # module:
  #   androidX: true
  #   androidPackage: my.package
  #   iosBundleIdentifier: my.package
  assets:
    - assets/images/start-page/
    - assets/images/img/
    - assets/images/wallet-page/
    - assets/images/otc/
    - assets/images/otc-campaign/
    - assets/pages/index.html
    - assets/images/shared/
    - assets/images/slider/
    - assets/images/icons/
    - assets/images/lightning-remit/
    - assets/cert/
flutter_icons:
  image_path: "assets/images/launcher/mobile-icon-ios.png"

  android: true
  ios: true

fonts:
  - family: Roboto
    fonts:
      - asset: Roboto-Italic.ttf
      - asset: Roboto-normal.ttf
  #  - lib/l10n/en.json
  #  - lib/l10n/zh.json
